### ISSUE TITLE
Consider loading Karla and PT Sans Narrow from Google Fonts

### ISSUE THREAD

**Issue by nateirwin** [trailheadlabs/outerspatial-map-library#103]
We're loading Karla and PT Sans Narrow from Google fonts for Manager and our public-facing web pages (https://fonts.googleapis.com/css?family=Karla:400,400i,700|PT+Sans+Narrow:400,700). We should consider doing the same for Map Library.

I go back and forth on this one. I like the idea of keeping Map Library's styles super simple, as this allows an org to "theme" an interactive map embedded in their own website without having to override a bunch of OuterSpatial-specific styles. On the other hand, there's something to be said for consistent presentation of content in popups, etc.

So maybe a good compromise is we can offload OuterSpatial-specific styling into map templates (like "/embed", "/print", etc.). This definitely requires some more thought and discussion, but wanted to create an issue so it's on our radar going forward.

**Comment by jmoe** [comment]
I am all for giving the agencies as little control over/influence on style as possible and pushing it to be consistent across all products and platforms. They all want to be special little flowers, but at then end of the day it hurts visitor experience to have to readjust to a new style everywhere you see the same content.

**Comment by nateirwin** [comment]
Yeah, me too. Our "recommended" method for embedded interactive maps into external web pages is through the use of iframes. Because of this, we can add Karla and PT Sans Narrow, and other styles, in the "embed" template to keep the Map Library experience as clean as possible.

The reason I go back-and-forth on this is because I can see use cases where an organization wants to embed a map into a web page on their site and have basic styling like link color, fonts, etc. trickle down from their page to the map. Map Library's CSS currently handles this fairly well, though there can still be conflicts if a page has a bunch of crummy CSS.

In the end, I think we should say that we'll only provide basic support for organizations that want to embed maps using Map Library and not iframes. It's not feasible for us to troubleshoot issues with an organization's website, but if the org is willing to take on this development work themselves, it would be good for us to at least give them a way to embed maps directly.

**Comment by ryanbranciforte** [comment]
We could potentially charge an hourly rate for more involved work on map embeds. I've been a bit more successful lately at adding in some pro services for data clean up. This could be similar and we can add into our proposals/contracts. Basically, we offer basic embed support, but more involved embeds would require additional resources and be billed hourly. I think SMF is a good example of a custom embed since that took quick a bit of work on our and Riley's side to pull off.

**Comment by nateirwin** [comment]
Going to close this one, as I just opened an issue to implement this into the "embed" and "print" templates in the OuterSpatial repo: https://github.com/trailheadlabs/outerspatial/issues/1495.
