### ISSUE TITLE
Closed status indicator not displaying for a POI

### ISSUE THREAD

**Issue by nateirwin** [trailheadlabs/outerspatial-map-library#106]
https://manager.outerspatial.com/6372/features/points_of_interest/257/info

![areas___outerspatial_manager](https://user-images.githubusercontent.com/10443/32743904-0f51b13a-c86b-11e7-9c55-b7a6ea042706.png)

**Comment by ryanjhodge** [comment]
This was because the map had not been upgraded to 7.1.7 yet. I just went in and re-saved it.
<img width="751" alt="screen shot 2017-11-13 at 1 11 08 pm" src="https://user-images.githubusercontent.com/4172213/32746843-2a85ca50-c874-11e7-8174-24bc88ba6ed1.png">

**Comment by nateirwin** [comment]
Ah, oops. Thanks!
