### ISSUE TITLE
Support zoom dependent rendering for OuterSpatial preset overlays

### ISSUE THREAD

**Issue by nateirwin** [trailheadlabs/outerspatial-map-library#111]
Moved here from https://github.com/trailheadlabs/outerspatial/issues/1250

**Comment by ryanjhodge** [comment]
Up on staging. Need help with prioritizing point types and setting the zoom ranges for priority ranks.

**Comment by ryanbranciforte** [comment]
This came up in call @nateirwin and I had with NAC today. They'll be excited about this.

**Comment by nateirwin** [comment]
I think we can hide/show "secondary" points of interest (basically anything other than trailheads, campgrounds, visitor centers, and entrances) at zoom level 14. This is what we're currently doing in iOS. May want to tweak this later, but this should suffice for now.
