### ISSUE TITLE
Improve "Get Directions" link

### ISSUE THREAD

**Issue by nateirwin** [trailheadlabs/outerspatial-map-library#112]
Not a huge priority because, to my knowledge, we haven't heard from any customers that it's not working well, but want to open a ticket to keep it on our radar. The current approach (linking to Apple Maps) works ok, but we may want to get fancy and do more intelligent detection of platform/browser and change the URL based on that.

I think we should go out and see how others are doing this across the web. We can document the different approaches in this issue, and tackle implementation once we've figured out a good approach.

**Comment by nateirwin** [comment]
Facebook links to "Here Maps": http://share.here.com/r/mylocation/e-eyJuYW1lIjoiQm9sc2EgQ2hpY2EgU3RhdGUgQmVhY2ggVmlzaXRvciBDZW50ZXIiLCJhZGRyZXNzIjoiMTc4NTEgUGFjaWZpYyBDb2FzdCBIaWdod2F5LCBIdW50aW5ndG9uIEJlYWNoLCBDYWxpZm9ybmlhIiwibGF0aXR1ZGUiOjMzLjY5NTEyNzksImxvbmdpdHVkZSI6LTExOC4wNDcwNTI3LCJwcm92aWRlck5hbWUiOiJmYWNlYm9vayIsInByb3ZpZGVySWQiOjEzNDIzNTYzMDkxODUwMjh9?link=addresses&fb_locale=en_US&ref=facebook. The URLs encoded though, so not sure what exactly's going on.

**Comment by nateirwin** [comment]
Foursquare links to Google Maps: http://maps.google.com/maps?daddr=39.719332952523615,-104.94975323943619

**Comment by nateirwin** [comment]
Yelp links to their own routing interface: https://www.yelp.com/map/triple-tree-cafe-denver?start=4408%20Decatur%20Street%2C%2080211

**Comment by nateirwin** [comment]
Given all that, my first take on our best approach is to default to Google Maps (using the same URL structure as Foursquare) but detect if the user is using iOS Safari and use Apple Maps (using the same URL structure we're currently using).

The other approach is to just default everything to Google Maps. It doesn't open the app consistently, if installed, but seems like there's not a good way to do that.

**Comment by ryanbranciforte** [comment]
👍
