### ISSUE TITLE
Ensure z-index is working properly for overlays

### ISSUE THREAD

**Issue by nateirwin** [trailheadlabs/outerspatial-map-library#121]
z-index for vector overlays does not seem to be working correctly. Currently, if a trails GeoJSON file loads after an areas GeoJSON file loads, the trails display underneath the areas in the map, making them impossible to select.

**Comment by nateirwin** [comment]
Here's a good map to test with: https://manager.outerspatial.com/3884/maps/builder/87.

**Comment by ryanjhodge** [comment]
Unable to review on staging, since I'm not added to the Golden Gate Org on Staging

**Comment by ryanbranciforte** [comment]
@ryanjhodge I added you to GGNPC org on staging and production.

**Comment by ryanjhodge** [comment]
Thanks! I tested and it's working properly.
