### ISSUE TITLE
GeoJSON with GeometryCollection displaying artifacts between geometries

### ISSUE THREAD

**Issue by nateirwin** [trailheadlabs/outerspatial-map-library#125]
To reproduce:

1. Go to https://www.outerspatial.com/builder_maps/92/edit
2. Zoom into the center area on the map

<img width="548" alt="map_builder___outerspatial" src="https://user-images.githubusercontent.com/10443/33959160-de4ecf68-e003-11e7-8c60-b1c850d775f4.png">

**Comment by ryanjhodge** [comment]
I've seen this before when the fill attribute is set for geometry collections
