### ISSUE TITLE
Search option not showing for SMF builder map when viewing on iPhone 7

### ISSUE THREAD

**Issue by ryanbranciforte** [trailheadlabs/outerspatial-map-library#126]
1. https://sheriffsmeadow.org/lands/#map-trigger
2. Here is when first loaded.

![img_1362](https://user-images.githubusercontent.com/2602563/34011540-3c0596de-e0c5-11e7-9e06-f81edf7c935e.PNG)

3. When in full screen mode. You'll notice the 'Search' option does partially show. 

![img_1363](https://user-images.githubusercontent.com/2602563/34011561-4b857a16-e0c5-11e7-8e10-7c0197840aaa.PNG)

Btw, looks great when you rotate the phone horizontal.

**Comment by ryanbranciforte** [comment]
Wondering if Search and Basemap finder could be set to not conflict with each other.

**Comment by ryanjhodge** [comment]
They can, we just need to figure out how we want to handle this situation.
What I can think of off the bat are:
1. Remove basemap switcher when they collide
1. Move the basemap switcher default positon to the top left by default
1. Move the basemap switcher to the top left when they collide
1. Shrink the basemap switcher to the size of the single buttons (e.g. home, zoom, locate) when they collide

**Comment by ryanbranciforte** [comment]
@nateirwin Should I see this as already updated on the SMF site, or does the map on their site still need to be updated to the new library? Just reviewed on their site and doesn't look any different.

**Comment by ryanbranciforte** [comment]
I just opened and saved the SMF map and it looks better now. Disregard last comment.
