### ISSUE TITLE
Geocoder tool rendering issue on mobile

### ISSUE THREAD

**Issue by nateirwin** [trailheadlabs/outerspatial-map-library#138]
![36989549-3f157b08-205f-11e8-9fd7-522205f03be6](https://user-images.githubusercontent.com/10443/37415034-1f8a9652-2770-11e8-920c-08fc139755d6.png)

**Comment by ryanjhodge** [comment]
@nateirwin Do we know what iOS version it was and whether if it was in portrait or landscape mode?

**Comment by ryanjhodge** [comment]
Yeah, tried reproducing using both XCode simulator and Chrome devtools to no avail.

**Comment by nateirwin** [comment]
I've asked NAC for more detail about this issue. Will update here when I hear back from them.

**Comment by nateirwin** [comment]
Re-opening this issue and updated the milestone as well. Here's the latest info from NAC:

> Sure, mine is iphone 7 Plus with ios 10.2 and I also tried on another iphone 6 and an Android phone and they all seem to have this issue when you switch it to landscape.

**Comment by nateirwin** [comment]
This is fixed. I was able to reproduce using Firefox.
