### ISSUE TITLE
Start clustering primary points of interest in the OuterSpatial preset

### ISSUE THREAD

**Issue by nateirwin** [trailheadlabs/outerspatial-map-library#143]
The tricky part about this is we'll need to merge campgrounds, trailheads, and "primary" points of interest (visitor centers and entrances) that are coming down from the points_of_interest endpoint into a single overlay. This would be a lot easier to do if either campgrounds and trailheads were just regular 'ole points of interest OR visitor centers and entrances had their own endpoints, but I think we can hack something together to make this work.

The clusters should use the same "unrounded" marker design we're using in the clusters in OuterSpatial Mobile. This marker is available in the OuterSpatial Mobile Sketch doc.

**Comment by nateirwin** [comment]
Has this been deployed someplace so we can test it? Being that this is a big piece of new functionality, I'm going to move back to "Needs Review" until we've had the opportunity to test.

**Comment by ryanjhodge** [comment]
Sure thing, I added a new developer example with said functionality, or I can push to staging and update the NAC map.  I wasnt sure if we are keeping the NAC map how it is for now, and rolling out everything at the same time or incrementally

**Comment by nateirwin** [comment]
k, I'll take a look at the developer example. Let's keep NAC as-is for now, as they may be using it.

**Comment by nateirwin** [comment]
What branch is this work in?

**Comment by ryanjhodge** [comment]
Docked popups

**Comment by nateirwin** [comment]
Cool, this is looking great! Closing.
