### ISSUE TITLE
Re-theme clustering icon

### ISSUE THREAD

**Issue by ryanjhodge** [trailheadlabs/outerspatial-map-library#154]
From #143

> The clusters should use the same "unrounded" marker design we're using in the clusters in OuterSpatial Mobile. This marker is available in the OuterSpatial Mobile Sketch doc.

**Comment by nateirwin** [comment]
This is done:

<img width="694" alt="outerspatial_preset__clustered____examples___outerspatial_map_library" src="https://user-images.githubusercontent.com/10443/42107924-4414a6b4-7b96-11e8-85d3-4aab5e175a8e.png">

If no custom cluster styles are specified in a map's config, this is how the clusters will look. It's similar to how clusters are implemented in iOS/Android. We can tweak this, if needed, but at least there's consistency across all of product now.

If custom cluster styles are specified, they'll continue to look like the old cluster style.
