### ISSUE TITLE
Refactor OuterSpatial preset to pull campgrounds and trailheads from points_of_interest static data

### ISSUE THREAD

**Issue by jmoe** [trailheadlabs/outerspatial-map-library#167]
Existing map builder configs need to be refactored to use the POI layer instead of the trailhead and campground layer.

**Comment by jmoe** [comment]
To be clear, we need a script or process to do this, not for it to actually be done yet. It will need to be executed shortly after run the the rest of the backend migration process.

**Comment by nateirwin** [comment]
This one's completely on me at this point, so I'm going to remove @jmoe from it for now.
