### ISSUE TITLE
Small zoom control not updating properly when setMaxZoom and setMinZoom called

### ISSUE THREAD

**Issue by nateirwin** [trailheadlabs/outerspatial-map-library#22]

**Comment by ryanjhodge** [comment]
Hmm, what is actually happening for this one? I tested it out by calling both of those methods from the browser console and the zoom control seems to be respecting the zoom limits I set.

**Comment by nateirwin** [comment]
I'll need to jump back in and take a look. But if I recall, it was like the small zoom control just didn't update when these methods were called so buttons weren't enabled/disabled properly.

**Comment by ryanjhodge** [comment]
Couldn't reproduce. May have been silently fixed when leaflet was upgraded.
