### ISSUE TITLE
Update geocoder to pull in results from the OuterSpatial API

### ISSUE THREAD

**Issue by nateirwin** [trailheadlabs/outerspatial-map-library#26]

**Comment by ryanbranciforte** [comment]
Does this mean that 'search' in .js would recognize and find trail, trailhead and area names? That would be really useful. I find it hard to locate the area I'm looking for if I don't know a town nearby.

**Comment by nateirwin** [comment]
Yep, exactly.

**Comment by ryanbranciforte** [comment]
Nice!

**Comment by nateirwin** [comment]
This will be really useful, but I think it may require some modifications to the API. Thoughts on this, @jmoe? Seems like an optimized search endpoint will be useful for numerous things – including OS Manager v2, OS Mobile v2, and OuterSpatial.js.

**Comment by nateirwin** [comment]
We can potentially just pull in areas for now. Not sure how to do this without exposing an access token, however. We can pull in GeoJSON from the static_data endpoints, but those are split up by organization, so they won't work for this purpose.

**Comment by ryanbranciforte** [comment]
This is directly related to the NAC project (NYC). A big part of that project is they want to improve search/filter within the map.

**Comment by ryanbranciforte** [comment]
@nateirwin @jmoe Do we have/need a ticket for API enhancements needed to support this?

**Comment by nateirwin** [comment]
Looks like there are several at least quasi-related issues open about this: https://github.com/trailheadlabs/outerspatial/issues?utf8=✓&q=is%3Aissue%20is%3Aopen%20search.

**Comment by nateirwin** [comment]
One thing we may be able to implement fully on the client-side without further API support is creating an index of vector features that are added to the map and making them searchable. We could do this directly in OuterSpatial Map Library and integrate it into the "geocoder" tool.

I actually think this may meet 80% or so of the need.

**Comment by ryanbranciforte** [comment]
Ok, cool, sounds good. 

I added this ticket, feel free to update as needed:
https://github.com/trailheadlabs/outerspatial/issues/1424

**Comment by nateirwin** [comment]
Just opened #42 to make vector features that have been added to the map available in the geocoder/search tool. Going to leave this issue open for when search gets added to the OuterSpatial API, but we should focus our energy on #42 for now.

**Comment by nateirwin** [comment]
Now that we have search working for OuterSpatial overlays that are added to the map, I don't see a need for this. We can revisit in the future if anothe requirement surfaces. Closing.
