### ISSUE TITLE
Open source OuterSpatial Map Builder

### ISSUE THREAD

**Issue by jgravois** [trailheadlabs/outerspatial-map-library#29]
the link to [OuterSpatial Map Builder](https://github.com/trailheadlabs/outerspatial-map-builder) in the README 404s.  i thought maybe you might still be in the process of _re_-open sourcing it, but it looks like it was already up in [March](https://github.com/trailheadlabs/outerspatial.js/commit/45170d53ca2c9eb8521d6b90ac4fdba0199e8c64)...

https://github.com/trailheadlabs/outerspatial.js#outerspatial-map-builder

ps. i'm here because @jmoe showed me your current ArcGIS Service integration while we were up in Tacoma. very cool!

**Comment by nateirwin** [comment]
Hey, @jgravois. Yes, we've made that repo private as we work through integrating Map Builder into the larger OuterSpatial platform and figure out how to isolate the platform-specific pieces from the rest of the code that would be useful to others.

I'll fix the link in the README, but will also leave this issue open and will update here when we figure out how we're going to _re_-open sourcing Map Builder.

**Comment by jgravois** [comment]
sounds good! looking forward to helping you think about how to extend your ArcGIS integration down the line.
