### ISSUE TITLE
Add class to container element in fullscreen mode

### ISSUE THREAD

**Issue by hitchcockwill** [trailheadlabs/outerspatial-map-library#34]
Going into fullscreen mode adds inline styles for fixed positioning. That's fine, but it will be nice to also add a class to the map container element so we can style externally based on that state.

Example of fullscreen mode right now:
`<div class="outerspatial" style="left: 0px; position: fixed; top: 0px;"><otherMapHTML /></div>`

Something like this would work:
`<div class="outerspatial fullscreen" style="left: 0px; position: fixed; top: 0px;"><otherMapHTML /></div>`

**Comment by nateirwin** [comment]
Done.
