### ISSUE TITLE
Re-theme controls based on design work

### ISSUE THREAD

**Issue by nateirwin** [trailheadlabs/outerspatial-map-library#43]
Controls:

![screenshot_8_31_17__4_14_pm](https://user-images.githubusercontent.com/10443/29947629-e1016560-8e67-11e7-9ca1-5f534c72fc7b.png)

![screenshot_8_31_17__4_19_pm](https://user-images.githubusercontent.com/10443/29947683-2e61093c-8e68-11e7-85f7-f102db0c6486.png)

![screenshot_8_31_17__4_21_pm](https://user-images.githubusercontent.com/10443/29947761-9780e9e6-8e68-11e7-8da7-01c96da5d6a8.png)

![loom_-_quick_videos__faster_than_typing](https://user-images.githubusercontent.com/10443/29947896-2eb83e22-8e69-11e7-9a92-630e5e1a8a03.png)

**Comment by nateirwin** [comment]
List:

- [ ] Notifications
- [ ] Attribution
- [ ] Share
- [ ] Print
- [ ] Fullscreen
- [ ] Home
- [ ] Locate
- [ ] Smallzoom
- [ ] Baselayer Switcher
- [ ] Popups (also apply basic styles to tooltips and infoboxes)
- [ ] Focus border

**Comment by ryanjhodge** [comment]
Holding off on share control until we implement it.

**Comment by nateirwin** [comment]
Just did a review, and have some feedback. In general things are looking great!

- Home and zoom controls look good
- The attribution control should have a bit more padding (C4C design in the screenshot):

![outerspatial-map-library_sketch](https://user-images.githubusercontent.com/10443/30663768-fefaecca-9e08-11e7-946d-f397e5720da0.png)

- Edit control looks good
- Fullscreen control looks good
- Locate control looks good
- Measure control looks good, but we may want to take a look at the styling for the side tools at some point. Not a priority for now though, so I just opened [another issue](https://github.com/trailheadlabs/outerspatial-map-library/issues/45) for this work.
- Print control looks good
- Let's increase the vertical space between the scale and attribution controls to match the vertical space between the bottom of the map and the attribution control. Let's also increase the left space between the edge of the map and the scale control:

<img width="393" alt="scale_control___examples___outerspatial_map_library" src="https://user-images.githubusercontent.com/10443/30664232-3b0d3622-9e0a-11e7-98cf-f390258f5395.png">

- Let's make the `font-weight` of the zoomdisplay control normal:

<img width="266" alt="zoomdisplay_control___examples___outerspatial_map_library" src="https://user-images.githubusercontent.com/10443/30664305-7405b71a-9e0a-11e7-970c-6ac5f520d9bf.png">

- For notifications, we need to move the default position of the map controls so they don't "collide". Also, the text should be left-aligned and I think we need to work on the font styling a bit:

<img width="446" alt="displaying_notifications___examples___outerspatial_map_library" src="https://user-images.githubusercontent.com/10443/30664400-cb9b087c-9e0a-11e7-982c-a4ee7fd854c3.png">

**Comment by ryanjhodge** [comment]
Some edits to the c4c design:
- Home, zoom, zoom display, locate, fullscreen, print, draw, [and share] tools will default to top right (not bottom right)
- Fullscreen, print, [and share] tools will not abut one another and will not align left of baselayer switcher. They will align vertically and separately in the top right like the rest of the controls.

**Comment by nateirwin** [comment]
Just thought of this, but we should also update the "zoombox" outline to match the focus outline of the map div.

**Comment by ryanjhodge** [comment]
<img width="383" alt="screen shot 2017-09-24 at 5 39 42 pm" src="https://user-images.githubusercontent.com/4172213/30787852-73eff0ae-a14f-11e7-8b36-f9e905576498.png">

Just re-themed the zoombox.  Should we also change the color of the popup close button to match the focus outline of the div map? There is no close button in the mockups from C4C.

**Comment by nateirwin** [comment]
Yep, that sounds good. It'll need a hover state as well.

**Comment by nateirwin** [comment]
- [ ] About the basemap selector, let's go ahead and move both it and the geocoder control over to the top left-hand side of the map. That'll buy us some time until we can get the new design fully implemented.

**Comment by nateirwin** [comment]
Broke two of the subtasks into #56 and #57. Closing now.
