### ISSUE TITLE
Create an OuterSpatial preset

### ISSUE THREAD

**Issue by nateirwin** [trailheadlabs/outerspatial-map-library#44]
This will allow organizations to pull in data from OuterSpatial without having to manually format popups, specify symbology, etc.

**Comment by ryanbranciforte** [comment]
Here is Alyssa's design. 

![29947761-9780e9e6-8e68-11e7-8da7-01c96da5d6a8](https://user-images.githubusercontent.com/2602563/31292888-eec2e424-aa89-11e7-8ee7-80dc2d1074fc.png)

**Comment by ryanbranciforte** [comment]
@jmoe After reviewing customer needs, this is second on the list to mobile and serve many customers at once (Mat-Su, Utah, FOSCT, and potentially Napa, BARTC, Santa Clara). 

Can you take this on, working with Nate as needed?

**Comment by nateirwin** [comment]
The initial preset is done, via https://github.com/trailheadlabs/outerspatial-map-library/pull/61. It doesn't yet include popup styling, symbology, etc., however, so going to leave this open until we get to those important pieces.
