### ISSUE TITLE
Map Builder preview won't load

### ISSUE THREAD

**Issue by ryanbranciforte** [trailheadlabs/outerspatial-map-library#46]
https://staging-manager.outerspatial.com/5185/maps/builder/23

![screen shot 2017-09-25 at 5 04 47 pm](https://user-images.githubusercontent.com/2602563/30837471-08bbdd9a-a21a-11e7-8325-e96cf634afff.png)

**Comment by nateirwin** [comment]
It looks like this is because the Map Builder preview is still using OuterSpatial Map Library 6.0.0, whereas Map Builder itself is using the new staging version. @ryanjhodge: Mind taking a look at this?
