### ISSUE TITLE
Basemap selector overlap with overview when there are many tools activated

### ISSUE THREAD

**Issue by ryanbranciforte** [trailheadlabs/outerspatial-map-library#47]
https://staging.outerspatial.com/builder_maps/23/embed#11/37.3027/-122.0918

![screen shot 2017-09-25 at 5 53 28 pm](https://user-images.githubusercontent.com/2602563/30837522-56ff9c9e-a21a-11e7-83f0-f9a6b09bb558.png)

**Comment by nateirwin** [comment]
The baseLayer Switcher still needs to be re-themed: #43. Closing this since we're already tracking there.
