### ISSUE TITLE
Can't close out polygon in measure tool

### ISSUE THREAD

**Issue by ryanbranciforte** [trailheadlabs/outerspatial-map-library#48]
1. activate measure
2. choose area
3. click around to create polygon
4. try to complete polygon, it won't let you. 

![screen shot 2017-09-25 at 5 55 37 pm](https://user-images.githubusercontent.com/2602563/30837561-a6ff5e32-a21a-11e7-9dbd-c77c486f5d56.png)

**Comment by nateirwin** [comment]
Tracking in #49.
