### ISSUE TITLE
Not seeing new controls in basemap on paper maps preview

### ISSUE THREAD

**Issue by ryanbranciforte** [trailheadlabs/outerspatial-map-library#51]
Testing on paper maps as requested. 

![screen shot 2017-09-27 at 1 19 28 pm](https://user-images.githubusercontent.com/2602563/30935796-a6f17480-a386-11e7-9e7e-290f9f77b6db.png)

**Comment by ryanjhodge** [comment]
This is because another branch of OuterSpatial was pushed to staging.

**Comment by ryanbranciforte** [comment]
Ok, lmk when and where we should be testing the new map controls.
