### ISSUE TITLE
Retheme baselayer switcher

### ISSUE THREAD

**Issue by nateirwin** [trailheadlabs/outerspatial-map-library#57]
![29947683-2e61093c-8e68-11e7-85f7-f102db0c6486](https://user-images.githubusercontent.com/10443/31092137-ae4136b6-a76a-11e7-9db6-0a3a3936dd28.png)

**Comment by nateirwin** [comment]
Just did a basic re-theme of switcher to make it work better with the rest of the control re-theme, but didn't implement this new design. Still needs some work.

**Comment by ryanjhodge** [comment]
One thing I want to point out for the review is, when the basemap layer list opens/closes the attribution control is removed from the map on layer list open and added again on layer list close.

On smaller maps, the layer list and attribution control were running into one another, and the attribution control did not look good on top of the layer list, nor on the bottom of if.

**Comment by ryanjhodge** [comment]
Also, I was unsure what the selected and on hover states should be? Is it the blue highlight around the section like in the sketch document? (all elements in the sketch document get the blue highlight hover state, so I wasn't sure if that was intentional or not)

**Comment by nateirwin** [comment]
Looks good on staging! Some feedback:

- [ ] In the original design, the preview images are not as tall and wider. I think we should try to reproduce the dimensions from the doc
- [ ] Let's add a hover state to the "Change" button. We can potentially just invert the colors... making the button fill the green color and changing the text to white.
- [ ] When the switcher control displays, tapping anywhere on the map should dismiss it without changing the basemap. Also, the map should not be interactive at all when the switcher control is visible. I was thinking we could display a div that intercepts/blocks all mouse events on top of the entire map when the switcher control is visible.
- [ ] Let's definitely add a highlight/hover border to the preview tiles. We can probably just change the border (and maybe add a halo/blur as well) to the green color we use to style the other map control hover states.
- [ ] Let's change "BASE LAYER" to "BASEMAP". I know we use "baseLayer" internally in Map Library, but I think the convention should be "basemap" in our user interfaces and documentation.

**Comment by nateirwin** [comment]
One more thing: It looks like mouseover/hover isn't working consistently for the top 1-2 "tiles". To reproduce:

1. Go to https://staging.outerspatial.com/builder_maps/31/edit
2. Click on "Change" in the basemap switcher
3. Hover over either the "OuterSpatial Outdoors" tile or the "Esri Imagery" tile and the halo/border appears inconsistently
