### ISSUE TITLE
Print control does not display on the map preview in Builder

### ISSUE THREAD

**Issue by ryanbranciforte** [trailheadlabs/outerspatial-map-library#76]
I *think* this is Map Library issue, but not sure. 

When creating or managing a builder map, the 'print' control does not show on the map preview. It seems to work for all the other tools, but not print. 

https://www.outerspatial.com/builder_maps/31/edit?login_token=80ec6c57d52c984ede412f9456816dae32e848ba7ddb5ae7e3615df3d529a45b&manager_redirect=https://manager.outerspatial.com/6372/maps/builder/31

![screen shot 2017-10-25 at 2 18 37 pm](https://user-images.githubusercontent.com/2602563/32023918-a583e974-b98f-11e7-9987-677c243970c6.png)

**Comment by nateirwin** [comment]
It does actually display in preview: https://manager.outerspatial.com/6372/maps/builder/31. It just collapses down into the right-hand toolbar, I believe because of size constraints.

**Comment by ryanbranciforte** [comment]
Got it, makes sense!
