### ISSUE TITLE
Add tags to OuterSpatial preset popups

### ISSUE THREAD

**Issue by ryanjhodge** [trailheadlabs/outerspatial-map-library#78]

**Comment by nateirwin** [comment]
Here are the tags I'm pulling into Mobile: https://github.com/trailheadlabs/outerspatial-mobile-aggregator/blob/master/clean.js#L215-L242.

And here's a screenshot showing how I'm displaying them:

![img_cc38b4951ea0-1](https://user-images.githubusercontent.com/10443/32519394-d79e72fa-c3c9-11e7-959e-3790a9b2bc77.jpeg)
