### ISSUE TITLE
Update overlays to OuterSpatial preset in existing Builder maps

### ISSUE THREAD

**Issue by ryanjhodge** [trailheadlabs/outerspatial-map-library#79]
- Add `preset: 'outerspatial'` property to the overlay configs
- Add `searchable: true` property to the overlay configs
- Remove `url` property from overlay configs

**Comment by nateirwin** [comment]
The script to do this update is ready to go. Waiting on @ryanjhodge to deploy a new version of Map Library before running it, however.

FYI, @ryanbranciforte: This script will update *all overlays that have been added to Builder Maps from OuterSpatial. This includes maps from Santa Clara County Parks, Visit Utah, City of Portland Parks and Recreation, etc. Currently the script overwrites any popup configuration that was done to these overlays previously, resetting them to the default style which pulls in the primary photo, description, website, etc. If this is not what you want, please let me know.

**Comment by ryanbranciforte** [comment]
@nateirwin Sounds good. 

FYI, for the Visit Utah maps which I am demoing tmrw at 11am PDT, there are not any photos, descriptions, website link, etc. They will be trained in Manager tmrw so they might start adding that info, unclear.

**Comment by nateirwin** [comment]
Now tracking here: https://github.com/trailheadlabs/outerspatial/issues/1466.
