### ISSUE TITLE
Fix area address formatting

### ISSUE THREAD

**Issue by ryanbranciforte** [trailheadlabs/outerspatial-map-library#84]
https://manager.outerspatial.com/6201/features/areas/82518/info

https://www.outerspatial.com/builder_maps/2/embed

![screen shot 2017-10-31 at 10 20 26 pm](https://user-images.githubusercontent.com/2602563/32261313-ee654200-be8a-11e7-8d16-65c299fbecc3.png)

![screen shot 2017-10-31 at 10 20 21 pm](https://user-images.githubusercontent.com/2602563/32261326-f75bc65e-be8a-11e7-9030-4abab4e60350.png)

**Comment by ryanjhodge** [comment]
Also on Mount Tamalpais State Park.

<img width="463" alt="screen shot 2017-11-01 at 11 48 18 am" src="https://user-images.githubusercontent.com/4172213/32288773-9647ae4e-befa-11e7-88fa-c8a25c3adf17.png">

**Comment by ryanjhodge** [comment]
The data is coming out of the API like this.

**Comment by nateirwin** [comment]
This is actually by design. Manager uses Mapzen's geocoder to allow users to select existing addresses. The object returned by Mapzen is then stringified and stored in OuterSpatial. In Mobile, I parse this and just use the "label" property for display.
