### ISSUE TITLE
No box shadows on upper right controls on OS manager feature editing pages

### ISSUE THREAD

**Issue by ryanjhodge** [trailheadlabs/outerspatial-map-library#85]
Remove `.outerspatial .leaflet-right .leaflet-control` selector.

<img width="534" alt="screen shot 2017-11-01 at 1 14 40 pm" src="https://user-images.githubusercontent.com/4172213/32292807-d9f36a6e-bf06-11e7-9437-21dcd3eb00c2.png">

**Comment by ryanjhodge** [comment]
This is being overridden in OuterSpatial Manager here:
https://github.com/trailheadlabs/outerspatial-manager/blob/master/src/components/map/map.scss

**Comment by nateirwin** [comment]
Btw, I just fixed this in OuterSpatial Manager.
