### ISSUE TITLE
Clustering not working for OuterSpatial preset point overlays

### ISSUE THREAD

**Issue by nateirwin** [trailheadlabs/outerspatial-map-library#87]
The following overlay config does not work properly:

    {
      "locationType": "trailheads",
      "organizationId": 6029,
      "preset": "outerspatial",
      "cluster": true,
      "searchable": true,
      "name": "City of Portland Parks and Recreation Trailheads",
      "styles": {
        "point": {
          "marker-library": "outerspatialsymbollibrary",
          "marker-symbol": "trailhead-white",
          "marker-color": "#32557d",
          "marker-size": "medium"
        }
      }
    }

**Comment by ryanbranciforte** [comment]
Funkiness with clustering

1. https://manager.outerspatial.com/6357/maps/builder/25

![screen shot 2017-11-03 at 11 14 28 pm](https://user-images.githubusercontent.com/2602563/32402975-d942e7a6-c0ec-11e7-89f5-59f87706c197.png)

2. Edit and then turn on clustering

![screen shot 2017-11-03 at 11 13 48 pm](https://user-images.githubusercontent.com/2602563/32402976-e4876dbc-c0ec-11e7-9900-0ac5753a3e90.png)

**Comment by ryanbranciforte** [comment]
I had to remove and reload those trailheads.

Another issue:

1. Edit and save cluster option
2. Then you can't open Configure Interactivity options.

![screen shot 2017-11-03 at 11 16 54 pm](https://user-images.githubusercontent.com/2602563/32402991-8724cb1e-c0ed-11e7-9346-13b6af7d1f0a.png)

**Comment by nateirwin** [comment]
Closing as this seems to be a totally different issue. Will open a new issue for this.

**Comment by nateirwin** [comment]
Also, one more thing about clustering: I think we should be very selective about when we turn it on for overlays. Overlays that have clustering turned on aren't "aware" of each other, so clusters can overlap, and I think in many cases having overlapping points is more usable/intuitive than having clustered.

It can be a useful feature in certain use cases, but it can also detract from the usability of the map.

**Comment by ryanbranciforte** [comment]
Makes sense. The scale dependent display will also help with this. Seems POIs are better to have only turn on at certain zoom levels, similar to the app.
