### ISSUE TITLE
Add selected indicator for GeoJSON overlay geometries

### ISSUE THREAD

**Issue by ryanbranciforte** [trailheadlabs/outerspatial-map-library#91]
This came up in the Utah meeting. Here is example.

1. https://www.outerspatial.com/builder_maps/70/embed -Hidden Canyon Trail
![screen shot 2017-11-02 at 3 23 18 pm](https://user-images.githubusercontent.com/2602563/32353230-cc4600a8-bfe1-11e7-858a-7875d8659757.png)

2. Here is the page it will be embedded into on their site
https://www.visitutah.com/places-to-go/most-visited-parks/zion/adventure-guide/hidden-canyon/

Since there are a bunch of trails in this area, it's hard to tell which one is Hidden Canyon. Even after you click on it, it's unclear the full route of the Hidden Canyon trail. 

Utah asked about a highlight or some way to indicate the full route of the trail when clicked.

**Comment by nateirwin** [comment]
Feedback on 7.1.8.1510716494704:

- [ ] Mouseover works for lines but not polygons or markers
- [ ] No selected indicator for markers. I think we can make this fairly generic and simple for now. Maybe just make it the same yellow color as the line/polygon selected color. A flat circle that displays at the base of the marker?
- [ ] Mouseover doesn't seem to work when another feature is selected

**Comment by ryanjhodge** [comment]
Just noticed the [`riseOnHover`](http://leafletjs.com/reference-1.2.0.html#marker-riseonhover) option yesterday, How about we use that for the marker selected indicator?

I intentionally turned off onHover for polygons, it got kind of irritating while using the map, I can turn it back on and see what you think.
