### ISSUE TITLE
Turning on directions doesn't persist in Manager

### ISSUE THREAD

**Issue by ryanbranciforte** [trailheadlabs/outerspatial-map-library#92]
1. Edit map - https://manager.outerspatial.com/6357/maps/builder/25
2. Turn on directions
![screen shot 2017-11-03 at 11 04 38 pm](https://user-images.githubusercontent.com/2602563/32402929-93f1b728-c0eb-11e7-887d-bfe1a0f3328a.png)

3. Open back up and directions is not selected. 
![screen shot 2017-11-03 at 11 04 08 pm](https://user-images.githubusercontent.com/2602563/32402930-9936dac4-c0eb-11e7-8b08-d3eb17cca9cf.png)

**Comment by nateirwin** [comment]
This is a Map Builder issue. Moved to the outerspatial repo: https://github.com/trailheadlabs/outerspatial/issues/1473.
