### ISSUE TITLE
Display closed status indicator in popup for OuterSpatial preset

### ISSUE THREAD

**Issue by nateirwin** [trailheadlabs/outerspatial-map-library#95]

**Comment by ryanjhodge** [comment]
Any thoughts about design? Perhaps after the title?

e.g. Contact Station/Kiosk (Closed)

**Comment by ryanjhodge** [comment]
@nateirwin Mind taking a screenshot of the design in mobile? I don't see it in the sketch document.

**Comment by nateirwin** [comment]
Probably makes sense to get you up and running with the iOS simulator so you can review how content's displayed in mobile. Let's work through that.
